language: c
sudo: required
dist: trusty
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y autotools-dev automake autoconf libtool libsystemd-daemon-dev libsystemd-journal-dev
script: ./autogen.sh && ./configure && make && make check
